### ISSUE TITLE
Unittest-Library (YUnit)

### ISSUE THREAD

**Issue by hoppfrosch** [RaptorX/SQLite#2]
Hi

where to get the unittest-library you are using? (namely <v2\Yunit\Yunit> and <v2\Yunit\Window>)

Trying to use Uberi's most recent Unittests (https://github.com/Uberi/Yunit) does not work - do you have a more recent personal version?

Cheers 
hoppfrosch

**Comment by RaptorX** [comment]
Hey.

Im using uberis' there's a v2 branch.
I only modified the `YunitWindow` a little bit visually.

https://github.com/Uberi/Yunit/tree/v2

Is thatThe one that doesn't work for you?
I can share my version in any case.
