### ISSUE TITLE
Ho I can return the value as string?

### ISSUE THREAD

**Issue by xmaxrayx** [RaptorX/SQLite#3]
Hi thanks for the library sorry idk about table object I tried this but it doesn't work for me ,the strange is I can see it (the value) on debug.
![image](https://github.com/RaptorX/SQLite/assets/101531362/23f24fae-9e50-46e6-8eb5-f370a3c4df02)

```
#Requires AutoHotkey v2.0
#Include 'SQLite.ahk'

dbFile := A_ScriptDir . "\testDBv1.db"
db := SQLite(dbFile , SQLITE_OPEN_READONLY)
new := db.Exec("SELECT password FROM users WHERE username = 'john' `;")
MsgBox(new.rows[1].data[1].value)
````

I got this error

```
Error: This value of type "SQLite" has no property named "__Item".

	013: new := db.Exec("SELECT password FROM users WHERE username = 'john' ;")
	015: MsgBox(new.headers[1])
▶	017: MsgBox(new.parent[1])
	019: hellow := "ss"
	021: MsgBox()

```

**Comment by RaptorX** [comment]
> Oh turn out because Vscode didn't save the File and I need to confirm to overwrite it ,sorry yeah the code `new.rows[1].data[1].value` works as intended.

you dont need to be that specific:

try:
`new[1].value`

the idea is that `new` is now a table, and you are accessing the first row `[1]` and the column named `value`

**Comment by xmaxrayx** [comment]
> > Oh turn out because Vscode didn't save the File and I need to confirm to overwrite it ,sorry yeah the code `new.rows[1].data[1].value` works as intended.
> 
> you dont need to be that specific:
> 
> try: `new[1].value`
> 
> The idea is that `new` is now a table, and you are accessing the first row `[1]` and the column named `value`
> 
> In your example you are accessing the "hidden" variables `row` and `data` that are just used internally to make it easier for you to do my suggestion :)




Hi, thanks for the care answers <3

idk I have test `new[1].value` without `data` array but I got empty string value seems because my SQL database was the issue? because I played with primary key for multi row.

````
#Requires AutoHotkey v2.0
#Include 'SQLite.ahk'

dbFile := A_ScriptDir . "\testDBv1.db"
db := SQLite(dbFile , SQLITE_OPEN_READONLY)
passwordValue := db.Exec("SELECT password FROM users WHERE username = 'john' `;")

MsgBox passwordValue[1].value   ;/return empty
MsgBox passwordValue.rows[1].value ;also return empty
MsgBox passwordValue.rows[1].data[1].value ;return the actually value "lol"
````
![image](https://github.com/RaptorX/SQLite/assets/101531362/1f80338b-c210-430b-953f-8e61f29e97d4)

**Comment by RaptorX** [comment]
No, you have to change `.value` for the actual name of the column

`passwordValue[1].password`

if you name your variables a different way it might make more sense:

```
#Requires AutoHotkey v2.0
#Include 'SQLite.ahk'

dbFile := A_ScriptDir . "\testDBv1.db"
db := SQLite(dbFile , SQLITE_OPEN_READONLY)
table  := db.Exec("SELECT password FROM users WHERE username = 'john' `;")

MsgBox table[1].password ; select the 1st row in the table and give me the password column.
```

**Comment by RaptorX** [comment]
try following the examples here: https://github.com/RaptorX/SQLite?tab=readme-ov-file#sqlite-wrapper-for-autohotkey

step by step, you might understand a little better how to use the managed interface.
